import 'package:firebase_core/firebase_core.dart';
import 'dart:async' show unawaited; // For non-awaitable tasks
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:stream_chat_flutter/stream_chat_flutter.dart' as stream;

import 'screens/splash_screen.dart';
import 'values/values.dart';
import 'controllers/contacts_controller.dart';
import 'controllers/user_controller.dart';
import 'controllers/auth_controller.dart';
import 'controllers/session_controller.dart';
import 'controllers/user_profile_controller.dart';
import 'controllers/ai_agent_controller.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure (or CI mock)
import 'services/performance/startup_optimization_service.dart';
import 'services/performance/enhanced_performance_monitor.dart';
import 'widgets/activity_detector.dart';
import 'widgets/pricing/current_price_consumer.dart';
import 'config/runtime_toggles.dart';
import 'services/shopping_lists/shopping_list_cache.dart';
import 'services/user/user_info_disk_cache.dart';
import 'utils/app_logger.dart';
import 'services/chat/chat_dependency_injector.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Set default language to avoid locale warnings.
  try {
    await FirebaseAuth.instance.setLanguageCode('en');
  } catch (_) {}

  // Activate App Check.
  try {
    await FirebaseAppCheck.instance.activate(
      androidProvider: kReleaseMode
          ? AndroidProvider.playIntegrity
          : AndroidProvider.debug,
      appleProvider: kReleaseMode
          ? AppleProvider.deviceCheck
          : AppleProvider.debug,
    );
  } catch (e) {
    AppLogger.w('AppCheck activation failed (continuing in debug): $e');
  }

  // Enable Firestore persistence asynchronously.
  unawaited(
    Future(() async {
      try {
        FirebaseFirestore.instance.settings = const Settings(
          persistenceEnabled: true,
          cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
        );
      } catch (_) {}
    }),
  );

  // Initialize core controllers.
  // Auth and Session controllers.
  Get.put(AuthController(), permanent: true);
  Get.lazyPut(() => SessionController(), fenix: true);
  Get.lazyPut(() => UserProfileController(), fenix: true);

  Get.lazyPut(() => UserController(), fenix: true);
  
  Get.lazyPut(() => ContactsController(), fenix: true);
  // AI Agent controller.
  Get.lazyPut(() => AIAgentController(), fenix: true);

  // Initialize chat dependencies.
  unawaited(
    ChatDependencyInjector.initializeChat().catchError((e) {
      AppLogger.w('Chat initialization failed: $e');
    }),
  );

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.light,
      statusBarIconBrightness: Brightness.light,
    ),
  );

  runApp(
    Builder(
      builder: (context) {
        // Defer heavy initialization.
        WidgetsBinding.instance.addPostFrameCallback((_) {
          // Initialize heavy services.
        });
        return MyApp();
      },
    ),
  );

  // Post-frame: perform heavier I/O & analytics without blocking first paint.
  WidgetsBinding.instance.addPostFrameCallback((_) {
    // Record first frame milestone for performance tracking
    EnhancedPerformanceMonitor.recordFirstFrame();

    // PHASE 1: Critical cache hydration (immediate)
    Future.wait([
      UserInfoDiskCache.instance.hydrate(),
      ShoppingListCache.instance.ensureSubscribed(),
    ]).whenComplete(() {
      if (kDebugMode) AppLogger.d('Critical caches hydrated.');
    });

    // PROGRESSIVE INITIALIZATION: Use optimized startup service
    StartupOptimizationService.initializeProgressiveStartup();
  });
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);

    // Check session validity when app resumes
    if (state == AppLifecycleState.resumed) {
      try {
        final userController = Get.find<UserController>();
        userController.checkSessionValidity();
      } catch (e) {
        AppLogger.w('Failed to check session validity: $e');
      }
    }
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    // Memoji preloading moved to StartupOptimizationService Phase 5
    // to prevent main thread blocking during startup
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<bool>(
      valueListenable: RuntimeToggles.instance.showPerformanceOverlay,
      builder: (context, showOverlay, _) => ActivityDetector(
        child: CurrentPriceProvider(child: _buildMaterialApp(showOverlay)),
      ),
    );
  }

  Widget _buildMaterialApp(bool showOverlay) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Shopple',
      showPerformanceOverlay: showOverlay && kDebugMode,
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: AppColors.background, // unify with navbar
        canvasColor: AppColors.background,
        cardColor: AppColors.surface,
        primaryColor: AppColors.primaryAccentColor,
        colorScheme: ColorScheme.dark(
          primary: AppColors.primaryAccentColor,
          secondary: AppColors.lightMauveBackgroundColor,
          surface: AppColors.surface,
          error: Colors.redAccent,
          onPrimary: Colors.white,
          onSecondary: Colors.white,
          onSurface: Colors.white,
          onError: Colors.white,
        ),
        appBarTheme: AppBarTheme(
          backgroundColor: AppColors.background, // match navbar/bg
          foregroundColor: Colors.white,
          systemOverlayStyle: SystemUiOverlayStyle.light,
        ),
      ),
      builder: (context, child) {
        // Wrap all routes with StreamChatTheme if chat is initialized
        // Use Get.isRegistered to check if StreamChatClient is available
        if (Get.isRegistered<stream.StreamChatClient>()) {
          try {
            final client = Get.find<stream.StreamChatClient>();
            return stream.StreamChat(
              client: client,
              child: stream.StreamChatTheme(
                data: stream.StreamChatThemeData.dark(),
                child: child ?? Container(),
              ),
            );
          } catch (e) {
            AppLogger.w('StreamChat client not available in builder: $e');
          }
        }
        return child ?? Container();
      },
      // Floating AI overlay removed (AI now has full screen tab)
      home: _buildHomeWithStreamChat(),
    );
  }

  Widget _buildHomeWithStreamChat() {
    return SplashScreen();
  }
}
